# Generated by Django 2.2.5 on 2019-09-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190907_1825'),
    ]

    operations = [
    ]
