# Generated by Django 2.2.5 on 2019-09-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190907_1826'),
    ]

    operations = [
    ]
