# Generated by Django 2.2.5 on 2019-09-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190908_1131'),
    ]

    operations = [
    ]
