# Generated by Django 2.2.5 on 2019-09-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190908_1145'),
    ]

    operations = [
    ]
