# Generated by Django 2.2.5 on 2019-09-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20190908_1153'),
    ]

    operations = [
    ]
